[carbin]
model = './carbin/authz_model.conf'

[cors]
allow_credentials = true
allow_headers = ['Authorization']
allow_methods = ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
allow_origin = ['http://localhost:8080']
expose_headers = []
max_age = '3600'

[db]
dsn = 'host=localhost user=test_user password=test_password dbname=test_db port=5433 sslmode=disable TimeZone=Asia/Bangkok'

[jwt]
email_secret = 'test_email_secret'
refresh_secret = 'test_refresh_secret'
secret = 'test_secret'

[labodt]
token = 'test_token'
url = 'http://localhost:3001'

[mail]
host = 'localhost'
password = 'test_password'
port = 587
username = 'test@example.com'

[pprof]
enable = false

[server]
host = 'localhost:8080'
host_name = 'http://localhost:8080'
port = '3000'
